### ISSUE TITLE
Convert VFB ind release to shell script to make

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#10]
Individuals files for VFB are currently built via a [shell script](https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/owl/vfb_ind_release.sh).  The main problem with this approach is that failure to build individual datasets doesn't trigger a Jenkins build failure.  The should be eaiser to acheive if we switch to using make with multiple targets.  This would also make it easy to update only specified datasets.

**Comment by Robbie1977** [comment]
All we need is a simple test that then passes an exit code other than 0 on failure.

**Comment by dosumis** [comment]
Have been playing with that.  Decided Make file would be easier. Happy to stick with shell if you are happier with it.  Don't have time to work on it myself now.
