### ISSUE TITLE
mavenise VFB_owl build

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#11]
Should be possible as all java libs used are on maven, including Jython (2.7b4).

**Comment by dosumis** [comment]
Test build using travis pulls owltools using maven and builds a compatible version of brain (same OWL-API version): https://github.com/dosumis/travis-jython-test

We should use this strategy to generate libs for OWL generation:

I've made a start at building the brain version we need with Jenkins. https://blanik.inf.ed.ac.uk:8079/view/OWL/job/build_Brain

Should pull OWLtools (&Jython 2.7?) via maven

Then need to set class paths (or jobs to copy over libs) as appropriate to drive build.

BTW - new version of build script in the works.  Generates report of OWL content. Still need the whole job to fail if one part does - either via modifications to the shell script, or rewriting as make.

**Comment by Robbie1977** [comment]
FYI Authorization key needed just waiting for some software to be installed to generate this.

**Comment by dosumis** [comment]
Any progress on this?  Would like to start running these builds on Jenkins again ASAP.

**Comment by dosumis** [comment]
Ping

**Comment by Robbie1977** [comment]
build brain is now working

**Comment by Robbie1977** [comment]
so far the Build_VFB_ind is working only issues seem to be internal:
```
*** Building Jenett2012 inds ***
debug1: Connection to port 3307 forwarding to 127.0.0.1 port 3306 requested.
debug1: channel 2: new [direct-tcpip]
Traceback (most recent call last):
  File "vfb_ind_runner.py", line 55, in <module>
    gen_ind_by_source(conn.cursor(), ont_dict, dataset)
  File "../mod/vfb_ind_tools.py", line 131, in gen_ind_by_source
    add_types_2_inds(vfb_ind, dc)
  File "../mod/vfb_ind_tools.py", line 34, in add_types_2_inds
    ont.addClass(d['clazBase']+d['claz'])
RuntimeError: maximum recursion depth exceeded (Java StackOverflowError)
Building Jenett2012 inds successful
```

**Comment by Robbie1977** [comment]
The problem is this:
http://stackoverflow.com/questions/8177073/python-maximum-recursion-depth-exceeded
but gets way more complicated in Jython

**Comment by dosumis** [comment]
Not sure it is. There's no recursive function in my Jython code.  So must be in Brain (or worse, the OWL-API).  I'll take a look at the Brain code + try to get a java stack trace.

**Comment by Robbie1977** [comment]
What version of Python is it expecting?

**Comment by Robbie1977** [comment]
Does this occur on your laptop?

**Comment by dosumis** [comment]
> Does this occur on your laptop?

No.  But have realised that this Jenkins job is not yet pointing at correct versions of OWLtools jar and brain jar.   Right now everything (including Jython) is running from the libs checked out from VFB_owl repo. (Path specified as var $CP).This needs to change.  Most importantly we versions of brain and owltools matched for OWL-API version.

This repo has a travis job with all the correct versions of jython, brain and owltools:
https://github.com/dosumis/travis-jython-test
https://github.com/dosumis/travis-jython-test/blob/master/.travis.yml

Brain needs to be the one built by this job:
https://blanik.inf.ed.ac.uk:8079/view/OWL/job/build_Brain/

We should also build OWLtools.  Pull latest for now - see: https://github.com/dosumis/travis-jython-test/blob/master/pom.xml.  I'll contact Heiko to make sure we have a stable build we can point to in future.

Jython could also be built separately via maven.

> What version of Python is it expecting?

Jython 2.7.0

We should probably also update java version.  I'm running 1.8 locally.

**Comment by dosumis** [comment]
Assume it's OK to close this.
