### ISSUE TITLE
Convert tables to InnoDB engine

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#14]
I've been switching tables in the OWL part of the flycircuit DB to InnoDB.  This allows foreign key constraints, delete cascades etc.  Not a high priority, but seems like a good idea to switch the rest of the DB. Leaving this up to you.

(Note - I've also switched the DB to UTF-8 as we need this for anything that goes to the website.  Main use case in this data is for Greeks - which are common in FB feature names.  Hoping there is no cleanup required following this change. Cleanup of FB feature names is easy as these are already auto-updated.)

Cheers,
David

**Comment by jefferis** [comment]
see http://stackoverflow.com/questions/3856435/how-to-convert-all-tables-from-myisam-into-innodb

```sql
SET @DATABASE_NAME = ''flycircuit";

SELECT  CONCAT('ALTER TABLE `', table_name, '` ENGINE=InnoDB;') AS sql_statements
FROM    information_schema.tables AS tb
WHERE   table_schema = @DATABASE_NAME
AND     `ENGINE` = 'MyISAM'
AND     `TABLE_TYPE` = 'BASE TABLE'
ORDER BY table_name DESC;


ALTER TABLE `spatdist_jfrc` ENGINE=InnoDB;
ALTER TABLE `registration` ENGINE=InnoDB;
ALTER TABLE `lsmxforms` ENGINE=InnoDB;
ALTER TABLE `flycircuit_flybase` ENGINE=InnoDB;
ALTER TABLE `flycircuit_driver_map` ENGINE=InnoDB;
ALTER TABLE `clusterv` ENGINE=InnoDB;
ALTER TABLE `clustering` ENGINE=InnoDB;
ALTER TABLE `cluster` ENGINE=InnoDB;
```

**Comment by jefferis** [comment]
I've made the changes in the dbs running on gjac and flybrain so should stick through any updates.
