### ISSUE TITLE
Decide on stable URIs for VFB individuals that are easy to resolve/mainatin

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#2]
In previous releases, we have used:

http://www.virtualflybrain.org/VFB_nnnnnnnn

This is not ideal as it is hard to devise a system for resolving entities from the web root.

Two alternatives:
http://www.virtualflybrain.org/owl/VFB_nnnnnnnn
http:/purl.obolibrary.org/obo/fbbt/VFB/VFB_nnnnnnnn

The latter potentially unifies control and is consistent with file resolution settings.  The former has the advantage of being simpler and directly under VFB control (no redirects required).

**Comment by Robbie1977** [comment]
Resolved to https://virtualflybrain.org/reports/VFB_nnnnnnnn
