### ISSUE TITLE
Set up Jenkins job to pull missing content from OWL (Jython) to neo4j

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#21]
- Requires latest vfb.owl (earlier versions will fail addition uniqueness constraints necessary for merge statements to work).
- Both need [python requests](http://docs.python-requests.org/en/master/).  Should be possible to install with pip.  
- Scripts: VFB_owl/src/code/owl2neo:
  - add_refs_for_anat.py neo_server_uri USR PWD path_to_owl_file
  - add_anonymous_types.py neo_server_uri USR PWD path_to_owl_file

@Robbie1977  - can you look into setting up dependencies?  Once ready, you can assign back to me.

**Comment by Robbie1977** [comment]
just run in this virtual env and eveything is installed:
```
source /disk/data/VFBTools/python-modules-2.6/bin/activate
```
Assuming you want python 2.6?

**Comment by dosumis** [comment]
Can this work with Jython?  (2.7 better)

**Comment by dosumis** [comment]
http://seletz.github.io/blog/2012/04/06/jython-classpath-virtualenv/

**Comment by Robbie1977** [comment]
not quite that simple unfortunately.
What version of Jython are you using?

**Comment by dosumis** [comment]
2.7.0

**Comment by Robbie1977** [comment]
getting it updated as it's currently 2.2 which has issues.

**Comment by dosumis** [comment]
OK.   We've been running it from a JAR up to now.  Question is how that could be combined with regular Jython imports.  Should be possible to package all into one JAR.

**Comment by Robbie1977** [comment]
Have you tried it under the virtual environment? (just use 2.7 instead of
2.6)

**Comment by Robbie1977** [comment]
which jenkins job is it running in?

**Comment by dosumis** [comment]
The owl conversion uses Jython from jar:
https://blanik.inf.ed.ac.uk:8079/view/OWL/job/Build_VFB_ind/
Build currently disabled by commenting out
(needs updating #5 )

**Comment by dosumis** [comment]
In https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/owl/vfb_ind_release.sh

All Jython scripts are run as: 

java -Xmx6000m -cp $CP"*" org.python.util.jython

**Comment by Robbie1977** [comment]
working through the error - resolving the port forwarding first: suspect jenkins isn't authorized for this ATM - ticket in
