### ISSUE TITLE
Review annotation mapping table, fill in gaps

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#26]
There are a few neuron annotations without mappings in the DB: 
https://github.com/VirtualFlyBrain/VFB_owl/blob/master/doc/annotation_map.tsv

@mmc46: Can you fill out the missing ones & I'll reload.

**Comment by mmc46** [comment]
Done and pushed. 
@dosumis Those annotations with missing types were added in January. Can I check that you've got the latest ones, added 2 weeks ago. For, for example 'protocerebral bridge 18 glomeruli type 2 neuron'.

**Comment by dosumis** [comment]
Doesn't look like this one is in the table: protocerebral bridge 18 glomeruli type 2 neuron

Generated table from DB today.  Perhaps you need to update mysql from Filmaker /R frames ?

**Comment by mmc46** [comment]
Can you check now? It's been updated. Sorry.

**Comment by dosumis** [comment]
Should be in here now:

https://github.com/VirtualFlyBrain/VFB_owl/blob/master/doc/annotation_map_report.tsv

This table is just a report of what's in the DB.   You can copy, paste lines from here to annotation_map.tsv table, then edit.  I'll then run the update.

**Comment by mmc46** [comment]
Can't see the new annotations there yet.

**Comment by dosumis** [comment]
Presumably not yet in DB then.  Busy now.  Let's work on this tomorrow.
