### ISSUE TITLE
Version PURL screw-up

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#29]
Please could we co-ordinate on this in future - things seems to have
gone badly wrong with communication on what is needed for these.
## Generic PURL Spec:

Each OWL file has an IRI and a version IRI.  The IRI should resolve to
the current version of the owl file.  The version IRI should resolve
to the specific release.  It should remain stable indefinitely.

PURL redirects are controlled via this GitHub repo: https://github.com/OBOFoundry/purl.obolibrary.org/

Redirects can act at the directory level or at the level of individual
files.  The latter can over-rule the former.

e.g. compare

http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl  (file redirect)
http://purl.obolibrary.org/obo/fbbt/vfb/Ito2013.owl (directory level
redirect)
## VFB owl file PURL spec:

We absolutely need PURL resolution for IRI and version IRI for the
main VFB release file

http://purl.obolibrary.org/obo/fbbt/vfb/vfb.owl
http://purl.obolibrary.org/obo/fbbt/vfb/YYYY-MM-DD/vfb.owl

It is acceptable for the latter to resolve to a zipped file.  It would
also be nice if the PURLs for individual OWL datasets
(e.g. Ito2013.owl) resolved too (both as current and version IRI). 
## Current status:

Current release used on VFB resolves OK.  (unzipped copy on site).
Version resolution is screwed up.

We have a directory level redirect for this

http://purl.obolibrary.org/obo/fbbt/vfb/
>
https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Current/src/owl/

This works for current releases of datasets + zipped vfb.owl.  As none
is advertised, I don't suppose that matters so much right now.  But it
doesn't work for versioned OWL files. This does, but only up to 

http://purl.obolibrary.org/obo/fbbt/vfb/2016-06-02

After this date - you switched to tag releases on GitHub which just provide
a zip of the whole repo.  Hard to see how this can ever work with PURL
spec above.
## Solution:

It is hard to see a complete fix for this that doesn't cause a PURL
maintenance headache - with new PURL specifications require for all
new releases.

The only thing I can think to do is to change the version IRIs for
future releases to:

http://purl.obolibrary.org/obo/fbbt/vfb/releases/YYYY-MM-DD/fu.owl

Version folder system should move back to regular folders and all version folders should be moved down to

https://raw.githubusercontent.com/VirtualFlyBrain/master/src/owl/releases

I can then do a directory level redirect 

http://purl.obolibrary.org/obo/fbbt/vfb/releases 
>
https://raw.githubusercontent.com/VirtualFlyBrain/VFB_owl/Master/src/owl/releases

For backwards compatibility I should probably also roll redirects for
existing folders 

e.g. 
http://purl.obolibrary.org/obo/fbbt/vfb/

I know this is not very elegant re GitHub repo usage and repo size.
Please let me know if you have a better solution.  Perhaps releases
should be hived off to a different repo?

**Comment by Robbie1977** [comment]
I've resolved all redirects assuming my syntax is all correct and works as expected.

Will test when push is accepted.

**Comment by dosumis** [comment]
Ta

**Comment by Robbie1977** [comment]
@dosumis probably best to discuss on the ticket rather than the pull request.

The relases such as http://purl.obolibrary.org/obo/fbbt/vfb/releases/YYYY-MM-DD/fu.owl is supported and working as well as http://purl.obolibrary.org/obo/fbbt/vfb/YYYY-MM-DD/fu.owl
