### ISSUE TITLE
LCN12 annotation

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#35]
We seem to have a rather huge number of these, with quite diverse morphologies. http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?id=FBbt_00100484

Is this annotation correct?

**Comment by mmc46** [comment]
It seems to be. They'll tile the lobula, but project to a specific region in the AVLP (target optic glomeruli).
There seems to be some subregion specificity, looking at all neurons, but AFAIK not yet described.

**Comment by dosumis** [comment]
Would be good to be able to trace where the assertion comes from.

**Comment by mmc46** [comment]
From work in the NBLAST paper and types described in Otsuna and now Panser.

(This is an issue that applies to any annotation of neuron types to images, which would be good to solve - there isn’t a way to add a reference)

**Comment by dosumis** [comment]
@Robbie1977 We should think about how to store this in the KB.  Could be comments or references on edges.  In this cas:

```cql
(:Individual { label 'Cha-F-000018' })
-[:SUBCLASSOF { comment: 'This mapping is based on..', PMID:123456 }]->
(:Class { label : 'lobula columnar neuron Lcn12' })
```

**Comment by Robbie1977** [comment]
Should be possible on both nodes and edges (as relevant) but should also be
an array or more likely a Json/dict as we need to link attribution, comment
and date info (maybe rating).
We should also think about a more general attribution on all nodes and
edges stating if officially curated (and from whom: VFB/FB) or user
submitted (or reasoned?).
It would need to be an iri ref to the curator/user data node as needs to
fit on edges too.

**Comment by dosumis** [comment]
* Evidence supporting assertions needs to go on edges that make the assertion, not nodes.
* AFAIK, there are limitations to what we can do with the data if we store maps as attributes as these need to be unpacked before they can be used.  Given this, perhaps it's better is we stick to simple attributes?  In this odd case where there are multiple lines of evidence supporting a mapping, we could potentially just make this clear in the comment.  Alternatively, we could make evidence nodes and link these to edges via node IDs/URIs.

**Comment by Robbie1977** [comment]
evidence needs to be on the edge directly or we risk drastically increasing our node count unessarily. 
Sorry I was expanding the spec to future proof

**Comment by dosumis** [comment]
RE Json object/dict on attribute: OLS stores maps as attribute values, but does so by packing them into strings:

e.g. 
```cql
MATCH (c:Class { iri: 'http://purl.obolibrary.org/obo/FBbt_00007238' }) return c.obo_xref
```
=> 
![image](https://cloud.githubusercontent.com/assets/112839/24191470/dbee3bc4-0ee3-11e7-897b-3a58ce376947.png)

I believe it is possible to unpack these in cypher (although haven't tried).  But certainly no good for querying.  Also need to be careful about storing unconstrained arbitrary structured documents like this - something Cypher is really designed to avoid.

**Comment by dosumis** [comment]
This is potentially relevant:

https://github.com/EBISPOT/OBAN

![image](https://github.com/EBISPOT/OBAN/raw/master/diagrams/oban%20db%20source%20model.png)

... although I wouldn't want to start putting intermediate nodes into assertions as this would screw up the OWL.  We could have something equivalent by just storing evidence IDs on edges. Not clear to me that we need to worry about numbers of nodes too much.

**Comment by dosumis** [comment]
Discussion of provenance models has moved here: 
https://github.com/VirtualFlyBrain/schema/issues/1
