### ISSUE TITLE
Review VFB.owl generated by scala by testing in pdb & on VFB 2.0

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_owl#46]

**Comment by dosumis** [comment]
Initial testing suggests type statements missed on v2:

![image.png](https://images.zenhubusercontent.com/595232dc61b4ca3b0a726d41/8de2f84c-aa06-402a-86c9-d4aa401a8e9f)

But type assertion seems to be in OWL:

![image.png](https://images.zenhubusercontent.com/595232dc61b4ca3b0a726d41/bd644624-6e96-49bd-9e02-9b07650b2999)

Need to check production instance and also to trace pipeline to see if latest OWL file is really being used.

**Comment by dosumis** [comment]
See:

pdb-dev
v2-dev

**Comment by Robbie1977** [comment]
stale ticket - reopen if still relevant
