### ISSUE TITLE
Missing individual VFB_00001330

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB_owl#9]
THMARCM-245M_seg1
VFB_00001330
FlyCircuit
http://flycircuit.tw/modules.php?name=clearpage&op=detail_table&idid=1330

http://www.virtualflybrain.org/owl/VFB_00001330
http://www.virtualflybrain.org/owl/VFBi_00001330/thumbnail.png

**Comment by mmc46** [comment]
This neuron is not part of the good registration set (good images), so it should't be shown. I think @dosumis is now only generating individuals for the neurons in the good set.

http://flybrain.mrc-lmb.cam.ac.uk/vfb/fc/good_images.txt

**Comment by dosumis** [comment]
This is correct
